# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: JSON Schema
#email: aaa@bzfx.net
description: The home of JSON Schema
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  json-schema-org
google_analytics: UA-99695987-1

# Build settings
markdown: kramdown
theme: minima

header_pages:
- specification.md
- examples.md
- implementations.md

exclude:
- README.md
- Gemfile
- node_modules

plugins:
  - jekyll-relative-links
  - jekyll-redirect-from
